---
- hosts: nodes
  sudo: no 
  vars:
    ELASTICSEARCH_HEAP_SIZE: 2g

    
  tasks:

   # Add some repositories and apt-get update
   - name: Add Repository --  Oracle Java
     apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present
   - name: Add Repository --  Oracle Java Source
     apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present

   - name: Add Repository key -- Oracle Java
     apt_key: keyserver=keyserver.ubuntu.com id=EEA14886
   
   - name: Add Repository --  Logstash
     apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' state=present

   - name: Add Repository --  Logstash Forwarder
     apt_repository: repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main' state=present
   
   - name: Add Repository --  Elasticsearch
     apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.6/debian stable main' state=present
   - name: Add Repository key -- Elasticsearch
     apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

   - name: Reload APT CACHE (apt-get update)
     apt: update_cache=yes

   - name: auto accept oracle jdk license
     shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

   # Update repositories cache and install "foo" package
   - name: Install package 
     apt: name={{item}} update_cache=yes
     with_items:
     - oracle-java8-installer
     - logstash
     - elasticsearch
     - nginx
     - apache2-utils

   - name: Custom PKI -- certs 
     file: path=/etc/pki/tls/certs state=directory
   - name: Custom PKI -- copy CRT
     copy: src=/home/nico/Documents/Scripts/ansible/elk/files/logstash-forwarder.crt dest=/etc/pki/tls/certs owner=root mode=0644
   - name: Custom PKI -- keyd 
     file: path=/etc/pki/tls/private state=directory
   - name: Custom PKI -- copy KEY
     copy: src=/home/nico/Documents/Scripts/ansible/elk/files/logstash-forwarder.key dest=/etc/pki/tls/private owner=root mode=0644

   - name: Custom ElasticSearch
     template: src=/home/nico/Documents/Scripts/ansible/elk/files/etc/default/elasticsearch.j2 dest=/etc/default/elasticsearch owner=root mode=0644
     template: src=/home/nico/Documents/Scripts/ansible/elk/files/etc/elasticsearch/elasticsearch.yaml.j2 dest=/etc/elasticsearch/elasticsearch.yaml owner=root mode=0644

   - name: Custom LogStash
     synchronize: src=/home/nico/Documents/Scripts/ansible/elk/files/etc/logstash/conf.d/ dest=/etc/logstash/conf.d 

   - name: Custom NGINX
     template: src=/home/nico/Documents/Scripts/ansible/elk/files/etc/nginx/sites-available/default.j2 dest=/etc/nginx/sites-available/default owner=root mode=0644

   - name: Restart NGINX
     service: name=nginx state=restarted

   - name: Enable service Elasticsearch
     service: name=elasticsearch enabled=yes

   - name: Change permissions on Elasticsaerch
     file: path=/var/lib/elasticsearch owner=elasticsearch group=elasticsearch mode=0755

   - name: Restart Elasticsearch
     service: name=elasticsearch state=restarted

   - name: Enable service Logstash
     service: name=logstash enabled=yes

   - name: Restart Logstash
     service: name=logstash state=restarted


